- name: "Install sublime if necessary ({{install_sublime}})"
  when: "'host_install_sublime' in group_names"
  block:
    - name: Install GPG key for SubLimeText
      become: true
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - name: Add sublime repositories into sources list
      become: true
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        state: present
        filename: sublime

    - name: Install packages
      become: true
      apt:
        update_cache: true
        pkg: sublime-text

    - name: "Copy {{ controller_sublime_config_dir }} for {{ sublime_usernames }}"
      become: true
      unarchive:
        copy: true
        src: "{{ controller_sublime_config_dir }}/user.tar.gz"
        dest: "/home/{{ sublime_username }}"
        mode: "0700"
        owner: "{{ sublime_username }}"
      with_items: "{{ sublime_usernames }}"
      loop_control:
        loop_var: sublime_username
      tags: configuration
