- hosts: vault_servers
  become: true
  vars:
    vault_server_db_destroy_confirm: true
    vault_server_storage_path: "/var/vault-testdata"

  roles:
    - server-db-destroy
    - server-tls-disable
    - server-db-create
    - server-unseal
    - server-db-init
    - server-tls-bootstrap
