- name: "Deploy kind if necessary ({{kind_deploy}})"
  when: kind_deploy
  block:
    - name: Get kind config temporary file path
      tempfile:
        state: file
        suffix: temp
      register: kind_cluster_config_temppath

    - name: "Write kind config in temp file ({{ kind_cluster_config_temppath.path }})"
      copy:
        dest: "{{ kind_cluster_config_temppath.path }}"
        content: "{{kind_cluster_config|to_nice_yaml}}"

    - name: "Deploy kind cluster"
      command:
        argv:
          - kind
          - create
          - cluster
          - "--config={{ kind_cluster_config_temppath.path }}"
    # - name: Use the registered var and the file module to remove the temporary file
    #   file:
    #     path: "{{ kind_cluster_config_temppath.path }}"
    #     state: absent
