- hosts: vault_hypervisor
  vars:
    vault_server_db_destroy_confirm: true
  roles:
    - makinj.vault.server_db_destroy
    - makinj.vault.server_tls_disable
- hosts: vault_server
  roles:
    - makinj.vault.server_db_create
    - makinj.vault.server_db_unseal
    # - makinj.vault.server_db_init_ca
    # - makinj.vault.server_db_init_int_ca
    # - makinj.vault.server_tls_bootstrap
#     # - server-tls-bootstrap
