- name: "Copy {{ controller_vim_config_dir }} for {{ vim_username }}"
  become: true
  unarchive:
    copy: true
    src: "{{ controller_vim_config_dir }}/"
    src: "{{ controller_vim_config_dir }}/user.tar.gz"
    dest: "/home/{{ vim_username }}"
    mode: "0600"
    owner: "{{ vim_username }}"

- name: "Clone vimrc files for {{ vim_username }}"
  become: true
  git:
    repo: https://github.com/amix/vimrc.git
    dest: "/home/{{ vim_username }}/.vim_runtime/"

- name: "Install vimrc_plugins for {{ vim_username }}"
  become: true
  command: "sudo -u {{ vim_username }} /home/{{ vim_username }}/.vim_runtime/install_awesome_vimrc.sh"
  ignore_errors: true
