- name: "Declare empty guest config for {{vagrant_guest_name}}" 
  set_fact:
    vagrant_guest_config: {}

- name: "Copy vagrant guest configs from host variables for {{vagrant_guest_name}}"
  set_fact:
    vagrant_guest_config: "{{ vagrant_guest_config | combine( [item | combine({'key':item.key[8:]})] | items2dict ) }}"
  with_items: "{{ dict(hostvars[vagrant_guest_name]) | dict2items}}"
  loop_control:
    label: "{{item.key}}"
  when: item.key.startswith('vagrant_')

# - name: build vagrant box add command
#   tags:
#     - vagrant_box_add
#   set_fact:
#     vagrant_box_add_command_args: "{{ (vagrant_box_add_command_args | default([])) + [item] }}"
#   when: item != omit
#   loop:
#     - "{{ vagrant_binary_path }}"
#     - box
#     - add
#     - "file:///{{vagrant_boxes_path}}/{{ hostvars[vagrant_guest_name].vagrant_box }}.box"
#     - "{{ (force_imports | default(False)) | ternary('--force', omit) }}"
#     - --name
#     - "{{ hostvars[vagrant_guest_name].vagrant_box }}"

# - name: "Import {{ hostvars[vagrant_guest_name].vagrant_box }} Box path for {{ vagrant_guest_name }}"
#   tags:
#     - vagrant_box_add
#   command:  
#     argv: "{{vagrant_box_add_command_args}}"
#   ignore_errors: true

- name: "Add guest name=\"{{ vagrant_guest_name }}\""
  set_fact:
    vagrant_guest_config: "{{ vagrant_guest_config | combine( {'name': vagrant_guest_name} ) }}"

- name: "Get stats of a background picture for {{vagrant_guest_name}}"
  ansible.builtin.stat:
    path: "{{vagrant_guest_config['workspaces_path']}}/{{vagrant_guest_name}}/sf/background.png"
  register: vagrant_guest_background_stat
- name: "Download random background for {{vagrant_guest_name}}"
  get_url:
    url: https://picsum.photos/1920/1200
    dest: "{{vagrant_guest_config['workspaces_path']}}/{{vagrant_guest_name}}/sf/background.png"
  when: "not vagrant_guest_background_stat.stat.exists"

- name: "Show vagrant guest config for {{vagrant_guest_name}}"
  debug:
    var: vagrant_guest_config
    verbosity: 2


- name: "Add to guest {{vagrant_guest_name}} to list"
  set_fact:
    vagrant_guest_configs: "{{ vagrant_guest_configs + [vagrant_guest_config] }}"
