- name: "Install fonts if necessary ({{install_fonts}})"
  when: host_install_fonts
  block:
  - name: "Configure each font"
    include_tasks: font.yaml

    with_items: "{{ font_urls }}"
    loop_control:
      loop_var: font_url
