- name: Deploy to vagrant guests
  hosts: "vagrant_guest:&running"
  roles: 
    - role: makinj.updates.install
      tags: ['always']

    - role: makinj.users.humans
      tags: ['user_configuration']
    
    - role: makinj.users.virtualbox_shared_folders
      tags: ['user_configuration']
    
    - role: makinj.zsh.install
      tags: ['base','zsh']
    
    - role: makinj.tmux.install
      tags: ['base','tmux']
    
    - role: makinj.vim.install
      tags: ['base','vim']
    
    - role: makinj.xfce.install
      tags: ['gui','xfce']
    
    - role: makinj.fonts.install
      tags: ['gui','fonts']
    
    - role: makinj.background.random
      tags: ['gui','background']
    - role: makinj.chrome.install
      tags: ['gui','chrome']
    
    - role: makinj.sublime.install
      tags: ['gui','sublime']
    
    # continue making installations conditional here
    # - role: makinj.docker.install
    #   tags: ['tools','infra','docker']
    
    # - role: common-provisioners/makinj.gcloud.install
    #   tags: ['tools','infra','gcloud_sdk']
    
    # - role: makinj.kubectl.install
    #   tags: ['tools','infra','k8s','kubectl']
    
    # - role: common-provisioners/makinj.kind.install
    #   tags: ['tools','infra','k8s','kind']
    
    # - role: common-makinj.golang.install
    #   tags: ['tools','infra','development','golang']
