- name: "Install kubectl if necessary ({{install_kubectl}})"
  when: "'host_install_kubectl' in group_names"
  block:
    - name: Install GPG key for GCP SDK
      become: true
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        state: present

    - name: Add kubernetes repositories into sources list
      become: true
      apt_repository:
        repo: "deb https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
        state: present
        filename: kubernetes

    - name: Install kubectl package
      become: true
      apt:
        update_cache: true
        pkg: 
          - kubectl
