- name: Stop vault service
  service:
    name: "{{ vault_server_service_name }}"
    state: stopped

- name: Destroy Storage directory
  file:
    path: "{{ vault_server_storage_path }}"
    state: absent
  when: vault_server_db_destroy_confirm | bool
